### ISSUE TITLE
 java.lang.IllegalStateException: Fragment already added: GifLoadingView

### ISSUE THREAD

**Issue by jaydroid1024** [Rogero0o/GifLoadingView#7]
2021-04-19 16:02:37.111 14795-14795/com.roger.gifloadingview E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.roger.gifloadingview, PID: 14795
    java.lang.IllegalStateException: Fragment already added: GifLoadingView{86e3f62 #1 }
        at android.app.FragmentManagerImpl.addFragment(FragmentManager.java:1694)
        at android.app.BackStackRecord.executeOps(BackStackRecord.java:776)
        at android.app.FragmentManagerImpl.executeOps(FragmentManager.java:2401)
        at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2196)
        at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2155)
        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2056)
        at android.app.FragmentManagerImpl$1.run(FragmentManager.java:719)
        at android.os.Handler.handleCallback(Handler.java:808)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7529)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by Rogero0o** [comment]
Should not show the same GifLoadingView twice, you can hide before want to show again
